version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_OPTS=--httpPort=8080
    networks:
      - jenkins-network
    restart: unless-stopped

  # PostgreSQL Database for Jenkins
  jenkins-db:
    image: postgres:15
    container_name: jenkins-db
    environment:
      POSTGRES_DB: jenkins
      POSTGRES_USER: jenkins
      POSTGRES_PASSWORD: jenkins_password
    volumes:
      - jenkins_db_data:/var/lib/postgresql/data
    networks:
      - jenkins-network
    restart: unless-stopped

  # SonarQube for code quality analysis
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - jenkins-network
    restart: unless-stopped

  # Nexus Repository for artifact management
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - nexus_data:/nexus-data
    networks:
      - jenkins-network
    restart: unless-stopped

volumes:
  jenkins_home:
  jenkins_db_data:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  nexus_data:

networks:
  jenkins-network:
    driver: bridge
