version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: sms-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: student_management
      MYSQL_USER: student_user
      MYSQL_PASSWORD: student_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sms-network
    command: --default-authentication-plugin=mysql_native_password

  # Spring Boot Backend
  backend:
    build: ./backend
    container_name: sms-backend
    environment:
      JWT_SECRET: mySecretKey123456789012345678901234567890
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/student_management?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    networks:
      - sms-network

  # React Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: sms-frontend
    ports:
      - "3001:5173"
    depends_on:
      - backend
    networks:
      - sms-network
    volumes:
      - ./:/app
      - /app/node_modules

volumes:
  mysql_data:

networks:
  sms-network:
    driver: bridge
